# Generated by Django 2.1.7 on 2019-06-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnochar', models.CharField(max_length=2)),
                ('lnoint', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cname', models.CharField(max_length=100)),
                ('cadress', models.CharField(max_length=100)),
                ('ccontact', models.CharField(max_length=50)),
                ('nth', models.CharField(default=True, max_length=50)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
