# Generated by Django 2.1.7 on 2019-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledata',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
